apiVersion: v1

kind: Service

metadata:
  name: db  # the worker app express the name of the postgres database to be 'db'
  labels:
    name: postgres-service
    app: demo-voting-app

specs:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    # paste results under postgres-pod metadata labels
    name: postgres-pod
    app: demo-voting-app