apiVersion: v1

kind: Service

metadata:
  name: redis # the name expressed by worker and voting-app pod
  labels:
    name: redis-service
    app: demo-voting-app

specs:
  # defaul type=ClusterIP , they are only accesible only via the cluster components (private)
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    # paste results under redis-pod metadata labels
    name: redis-pod
    app: demo-voting-app