apiVersion: v1

kind: Pod

metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app  # they are all part of the same app

spec:
  containers:
    - name: voting-app
      image: kodecloud/examplevotingapp_result:v1
      ports:
      - containerPort: 80
      